
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/STARTER-team02
owner: ucsb-cs156-s24
repo_name: STARTER-team02
pull_requests: [{"author":{"id":"U_kgDOB3E2LA","is_bot":false,"login":"sanilkatula","name":""},"headRefName":"sanil---fix-dates-controller","number":2,"title":"sk - fixed UCSBDatesController.java","url":"https://github.com/ucsb-cs156-s24/STARTER-team02/pull/2"},{"author":{"id":"MDQ6VXNlcjQzNzgzODc3","is_bot":false,"login":"yuxiaolejs","name":"Unics Yu"},"headRefName":"main","number":1,"title":"[fix] wrong swagger param for UCSBDates/post","url":"https://github.com/ucsb-cs156-s24/STARTER-team02/pull/1"}]
